language: rust

rust:
- nightly

script:
- cargo build
- cargo test

cache: cargo

before_install:
- sudo add-apt-repository ppa:team-xbmc/ppa -y
- sudo apt-get update -qq

install:
- sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/adam-*;
